### PR TITLE
Multiple minor improvements, more unification

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by tboerger** [comment]
Depends on https://github.com/drone/drone-go/pull/15

**Comment by jackspirou** [comment]
Not sure why the build is failing, even if I re-run with the error below: 

```bash
go test -cover ./...
# github.com/drone-plugins/drone-ssh
./main_test.go:32: undefined: drone.NewStringSlice
```

`drone.NewStringSlice` was adding in PR https://github.com/drone/drone-go/pull/15.

LGTM

**Comment by tboerger** [comment]
Tests are fine now.

**Comment by nlf** [comment]
LGTM

**Pull request merged**
